"""dropDataWindowToCreateNew

Revision ID: 4eef96afd976
Revises: 02c770fae3df
Create Date: 2021-12-23 23:12:17.808727

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4eef96afd976'
down_revision = '02c770fae3df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_datawindow_accountId', table_name='datawindow')
    op.drop_index('ix_datawindow_create_ts', table_name='datawindow')
    op.drop_index('ix_datawindow_resultId', table_name='datawindow')
    op.drop_index('ix_datawindow_taskId', table_name='datawindow')
    op.drop_index('ix_datawindow_update_ts', table_name='datawindow')
    op.drop_table('datawindow')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('datawindow',
    sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('create_ts', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('update_ts', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('accountId', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('taskId', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('resultId', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.Column('file_path', sa.VARCHAR(length=100), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False),
    sa.Column('startIdx', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('startVal', sa.NUMERIC(precision=26, scale=18), server_default=sa.text('0.0'), autoincrement=False, nullable=False),
    sa.Column('firstIdx', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('firstVal', sa.NUMERIC(precision=26, scale=18), server_default=sa.text('0.0'), autoincrement=False, nullable=False),
    sa.Column('highestIdx', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('highestVal', sa.NUMERIC(precision=26, scale=18), server_default=sa.text('0.0'), autoincrement=False, nullable=False),
    sa.Column('lastIdx', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('lastVal', sa.NUMERIC(precision=26, scale=18), server_default=sa.text('0.0'), autoincrement=False, nullable=False),
    sa.Column('date', sa.VARCHAR(length=10), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False),
    sa.Column('firstTs', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('highestTs', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('lastTs', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('startTs', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='datawindow_pkey'),
    sa.UniqueConstraint('id', name='datawindow_id_key')
    )
    op.create_index('ix_datawindow_update_ts', 'datawindow', ['update_ts'], unique=False)
    op.create_index('ix_datawindow_taskId', 'datawindow', ['taskId'], unique=False)
    op.create_index('ix_datawindow_resultId', 'datawindow', ['resultId'], unique=False)
    op.create_index('ix_datawindow_create_ts', 'datawindow', ['create_ts'], unique=False)
    op.create_index('ix_datawindow_accountId', 'datawindow', ['accountId'], unique=False)
    # ### end Alembic commands ###
