"""initdb

Revision ID: 530fa814c6d1
Revises: 
Create Date: 2021-06-02 14:35:44.241007

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '530fa814c6d1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candles',
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('src', sa.SmallInteger(), nullable=True),
    sa.Column('ts', sa.BigInteger(), nullable=True),
    sa.Column('open', sa.Numeric(precision=36, scale=18), nullable=True),
    sa.Column('high', sa.Numeric(precision=36, scale=18), nullable=True),
    sa.Column('low', sa.Numeric(precision=36, scale=18), nullable=True),
    sa.Column('close', sa.Numeric(precision=36, scale=18), nullable=True),
    sa.Column('vol', sa.Numeric(precision=36, scale=18), nullable=True),
    sa.Column('volCcy', sa.Numeric(precision=36, scale=18), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tickers',
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('src', sa.SmallInteger(), nullable=True),
    sa.Column('instType', sa.String(length=16), nullable=True),
    sa.Column('instId', sa.String(length=32), nullable=True),
    sa.Column('last', sa.Numeric(precision=36, scale=18), nullable=True),
    sa.Column('lastSz', sa.Numeric(precision=36, scale=18), nullable=True),
    sa.Column('askPx', sa.Numeric(precision=36, scale=18), nullable=True),
    sa.Column('askSz', sa.Numeric(precision=36, scale=18), nullable=True),
    sa.Column('bidPx', sa.Numeric(precision=36, scale=18), nullable=True),
    sa.Column('bidSz', sa.Numeric(precision=36, scale=18), nullable=True),
    sa.Column('open24h', sa.Numeric(precision=36, scale=18), nullable=True),
    sa.Column('high24h', sa.Numeric(precision=36, scale=18), nullable=True),
    sa.Column('low24h', sa.Numeric(precision=36, scale=18), nullable=True),
    sa.Column('volCcy24h', sa.Numeric(precision=36, scale=18), nullable=True),
    sa.Column('vol24h', sa.Numeric(precision=36, scale=18), nullable=True),
    sa.Column('sodUtc0', sa.Numeric(precision=36, scale=18), nullable=True),
    sa.Column('sodUtc8', sa.Numeric(precision=36, scale=18), nullable=True),
    sa.Column('ts', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tickers')
    op.drop_table('candles')
    # ### end Alembic commands ###
