"""init

Revision ID: 657f7a872098
Revises: 71dfd403dbb0
Create Date: 2021-12-19 23:26:22.802637

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '657f7a872098'
down_revision = '71dfd403dbb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('create_ts', sa.BigInteger(), nullable=False),
    sa.Column('update_ts', sa.BigInteger(), nullable=False),
    sa.Column('loginId', sa.String(length=32), nullable=False),
    sa.Column('password', sa.String(length=70), nullable=False),
    sa.Column('valid', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('loginId')
    )
    op.create_index(op.f('ix_account_create_ts'), 'account', ['create_ts'], unique=False)
    op.create_index(op.f('ix_account_update_ts'), 'account', ['update_ts'], unique=False)
    op.create_table('token',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('create_ts', sa.BigInteger(), nullable=False),
    sa.Column('update_ts', sa.BigInteger(), nullable=False),
    sa.Column('accountId', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('token', sa.String(length=32), nullable=False),
    sa.Column('expire', sa.Integer(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index(op.f('ix_token_accountId'), 'token', ['accountId'], unique=False)
    op.create_index(op.f('ix_token_create_ts'), 'token', ['create_ts'], unique=False)
    op.create_index(op.f('ix_token_update_ts'), 'token', ['update_ts'], unique=False)
    op.drop_table('tickers')
    op.drop_table('candles')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candles',
    sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('src', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('ts', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('open', sa.NUMERIC(precision=36, scale=18), autoincrement=False, nullable=True),
    sa.Column('high', sa.NUMERIC(precision=36, scale=18), autoincrement=False, nullable=True),
    sa.Column('low', sa.NUMERIC(precision=36, scale=18), autoincrement=False, nullable=True),
    sa.Column('close', sa.NUMERIC(precision=36, scale=18), autoincrement=False, nullable=True),
    sa.Column('vol', sa.NUMERIC(precision=36, scale=18), autoincrement=False, nullable=True),
    sa.Column('volCcy', sa.NUMERIC(precision=36, scale=18), autoincrement=False, nullable=True),
    sa.Column('instId', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('instType', sa.VARCHAR(length=16), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='candles_pkey')
    )
    op.create_table('tickers',
    sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('src', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('instType', sa.VARCHAR(length=16), autoincrement=False, nullable=True),
    sa.Column('instId', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('last', sa.NUMERIC(precision=36, scale=18), autoincrement=False, nullable=True),
    sa.Column('lastSz', sa.NUMERIC(precision=36, scale=18), autoincrement=False, nullable=True),
    sa.Column('askPx', sa.NUMERIC(precision=36, scale=18), autoincrement=False, nullable=True),
    sa.Column('askSz', sa.NUMERIC(precision=36, scale=18), autoincrement=False, nullable=True),
    sa.Column('bidPx', sa.NUMERIC(precision=36, scale=18), autoincrement=False, nullable=True),
    sa.Column('bidSz', sa.NUMERIC(precision=36, scale=18), autoincrement=False, nullable=True),
    sa.Column('open24h', sa.NUMERIC(precision=36, scale=18), autoincrement=False, nullable=True),
    sa.Column('high24h', sa.NUMERIC(precision=36, scale=18), autoincrement=False, nullable=True),
    sa.Column('low24h', sa.NUMERIC(precision=36, scale=18), autoincrement=False, nullable=True),
    sa.Column('volCcy24h', sa.NUMERIC(precision=36, scale=18), autoincrement=False, nullable=True),
    sa.Column('vol24h', sa.NUMERIC(precision=36, scale=18), autoincrement=False, nullable=True),
    sa.Column('sodUtc0', sa.NUMERIC(precision=36, scale=18), autoincrement=False, nullable=True),
    sa.Column('sodUtc8', sa.NUMERIC(precision=36, scale=18), autoincrement=False, nullable=True),
    sa.Column('ts', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='tickers_pkey')
    )
    op.drop_index(op.f('ix_token_update_ts'), table_name='token')
    op.drop_index(op.f('ix_token_create_ts'), table_name='token')
    op.drop_index(op.f('ix_token_accountId'), table_name='token')
    op.drop_table('token')
    op.drop_index(op.f('ix_account_update_ts'), table_name='account')
    op.drop_index(op.f('ix_account_create_ts'), table_name='account')
    op.drop_table('account')
    # ### end Alembic commands ###
