"""newDataWindow

Revision ID: 688b33ed73a2
Revises: 4eef96afd976
Create Date: 2021-12-23 23:13:25.266945

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '688b33ed73a2'
down_revision = '4eef96afd976'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('datawindow',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('create_ts', sa.BigInteger(), nullable=False),
    sa.Column('update_ts', sa.BigInteger(), nullable=False),
    sa.Column('accountId', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('taskId', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('resultId', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('date', sa.String(length=10), server_default='', nullable=False),
    sa.Column('file_path', sa.String(length=100), server_default='', nullable=False),
    sa.Column('startIdx', sa.Integer(), server_default='0', nullable=False),
    sa.Column('startTs', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('startVal', sa.Numeric(precision=26, scale=18), server_default='0.0', nullable=False),
    sa.Column('firstIdx', sa.Integer(), server_default='0', nullable=False),
    sa.Column('firstVal', sa.Numeric(precision=26, scale=18), server_default='0.0', nullable=False),
    sa.Column('firstTs', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('highestIdx', sa.Integer(), server_default='0', nullable=False),
    sa.Column('highestVal', sa.Numeric(precision=26, scale=18), server_default='0.0', nullable=False),
    sa.Column('highestTs', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('lastIdx', sa.Integer(), server_default='0', nullable=False),
    sa.Column('lastVal', sa.Numeric(precision=26, scale=18), server_default='0.0', nullable=False),
    sa.Column('lastTs', sa.BigInteger(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_datawindow_accountId'), 'datawindow', ['accountId'], unique=False)
    op.create_index(op.f('ix_datawindow_create_ts'), 'datawindow', ['create_ts'], unique=False)
    op.create_index(op.f('ix_datawindow_resultId'), 'datawindow', ['resultId'], unique=False)
    op.create_index(op.f('ix_datawindow_taskId'), 'datawindow', ['taskId'], unique=False)
    op.create_index(op.f('ix_datawindow_update_ts'), 'datawindow', ['update_ts'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_datawindow_update_ts'), table_name='datawindow')
    op.drop_index(op.f('ix_datawindow_taskId'), table_name='datawindow')
    op.drop_index(op.f('ix_datawindow_resultId'), table_name='datawindow')
    op.drop_index(op.f('ix_datawindow_create_ts'), table_name='datawindow')
    op.drop_index(op.f('ix_datawindow_accountId'), table_name='datawindow')
    op.drop_table('datawindow')
    # ### end Alembic commands ###
