"""add cloumn

Revision ID: 71dfd403dbb0
Revises: 530fa814c6d1
Create Date: 2021-06-03 09:22:47.054672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71dfd403dbb0'
down_revision = '530fa814c6d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candles', sa.Column('instId', sa.String(length=32), nullable=True))
    op.add_column('candles', sa.Column('instType', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candles', 'instType')
    op.drop_column('candles', 'instId')
    # ### end Alembic commands ###
