"""taskCanSaveAndParse

Revision ID: af72fbb98774
Revises: b9263973804f
Create Date: 2022-01-23 13:58:17.085355

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'af72fbb98774'
down_revision = 'b9263973804f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kepttask',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('create_ts', sa.BigInteger(), nullable=False),
    sa.Column('update_ts', sa.BigInteger(), nullable=False),
    sa.Column('accountId', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('product', sa.String(length=36), nullable=False),
    sa.Column('startDate', sa.String(length=10), nullable=False),
    sa.Column('endDate', sa.String(length=10), nullable=False),
    sa.Column('taskType', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('processing', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('percentage', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('resultId', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('params', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_kepttask_accountId'), 'kepttask', ['accountId'], unique=False)
    op.create_index(op.f('ix_kepttask_create_ts'), 'kepttask', ['create_ts'], unique=False)
    op.create_index(op.f('ix_kepttask_update_ts'), 'kepttask', ['update_ts'], unique=False)
    op.create_table('savedtask',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('create_ts', sa.BigInteger(), nullable=False),
    sa.Column('update_ts', sa.BigInteger(), nullable=False),
    sa.Column('accountId', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('product', sa.String(length=36), nullable=False),
    sa.Column('startDate', sa.String(length=10), nullable=False),
    sa.Column('endDate', sa.String(length=10), nullable=False),
    sa.Column('taskType', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('processing', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('percentage', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('resultId', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('params', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_savedtask_accountId'), 'savedtask', ['accountId'], unique=False)
    op.create_index(op.f('ix_savedtask_create_ts'), 'savedtask', ['create_ts'], unique=False)
    op.create_index(op.f('ix_savedtask_update_ts'), 'savedtask', ['update_ts'], unique=False)
    op.add_column('executiontask', sa.Column('params', sa.Text(), nullable=True))
    op.add_column('executiontask', sa.Column('taskType', sa.SmallInteger(), server_default='0', nullable=False))
    op.drop_column('executiontask', 'windowSize')
    op.drop_column('executiontask', 'windowUnit')
    op.drop_column('executiontask', 'increment')
    op.create_unique_constraint(None, 'sharerequest', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sharerequest', type_='unique')
    op.add_column('executiontask', sa.Column('increment', sa.SMALLINT(), autoincrement=False, nullable=False))
    op.add_column('executiontask', sa.Column('windowUnit', sa.VARCHAR(length=1), autoincrement=False, nullable=False))
    op.add_column('executiontask', sa.Column('windowSize', sa.SMALLINT(), autoincrement=False, nullable=False))
    op.drop_column('executiontask', 'taskType')
    op.drop_column('executiontask', 'params')
    op.drop_index(op.f('ix_savedtask_update_ts'), table_name='savedtask')
    op.drop_index(op.f('ix_savedtask_create_ts'), table_name='savedtask')
    op.drop_index(op.f('ix_savedtask_accountId'), table_name='savedtask')
    op.drop_table('savedtask')
    op.drop_index(op.f('ix_kepttask_update_ts'), table_name='kepttask')
    op.drop_index(op.f('ix_kepttask_create_ts'), table_name='kepttask')
    op.drop_index(op.f('ix_kepttask_accountId'), table_name='kepttask')
    op.drop_table('kepttask')
    # ### end Alembic commands ###
