"""execution

Revision ID: b17f67e24440
Revises: 657f7a872098
Create Date: 2021-12-20 12:36:48.688408

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b17f67e24440'
down_revision = '657f7a872098'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('datawindow',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('create_ts', sa.BigInteger(), nullable=False),
    sa.Column('update_ts', sa.BigInteger(), nullable=False),
    sa.Column('accountId', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('taskId', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('resultId', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('file_path', sa.String(length=100), server_default='', nullable=False),
    sa.Column('startIdx', sa.Integer(), server_default='0', nullable=False),
    sa.Column('startVal', sa.Numeric(precision=26, scale=18), server_default='0.0', nullable=False),
    sa.Column('endIdx', sa.Integer(), server_default='0', nullable=False),
    sa.Column('firstIdx', sa.Integer(), server_default='0', nullable=False),
    sa.Column('firstVal', sa.Numeric(precision=26, scale=18), server_default='0.0', nullable=False),
    sa.Column('highestIdx', sa.Integer(), server_default='0', nullable=False),
    sa.Column('highestVal', sa.Numeric(precision=26, scale=18), server_default='0.0', nullable=False),
    sa.Column('lastIdx', sa.Integer(), server_default='0', nullable=False),
    sa.Column('lastVal', sa.Numeric(precision=26, scale=18), server_default='0.0', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_datawindow_accountId'), 'datawindow', ['accountId'], unique=False)
    op.create_index(op.f('ix_datawindow_create_ts'), 'datawindow', ['create_ts'], unique=False)
    op.create_index(op.f('ix_datawindow_resultId'), 'datawindow', ['resultId'], unique=False)
    op.create_index(op.f('ix_datawindow_taskId'), 'datawindow', ['taskId'], unique=False)
    op.create_index(op.f('ix_datawindow_update_ts'), 'datawindow', ['update_ts'], unique=False)
    op.create_table('executionresult',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('create_ts', sa.BigInteger(), nullable=False),
    sa.Column('update_ts', sa.BigInteger(), nullable=False),
    sa.Column('accountId', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('taskId', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('windowCount', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('successCount', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('timeUsed', sa.SmallInteger(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_executionresult_accountId'), 'executionresult', ['accountId'], unique=False)
    op.create_index(op.f('ix_executionresult_create_ts'), 'executionresult', ['create_ts'], unique=False)
    op.create_index(op.f('ix_executionresult_taskId'), 'executionresult', ['taskId'], unique=False)
    op.create_index(op.f('ix_executionresult_update_ts'), 'executionresult', ['update_ts'], unique=False)
    op.create_table('executiontask',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('create_ts', sa.BigInteger(), nullable=False),
    sa.Column('update_ts', sa.BigInteger(), nullable=False),
    sa.Column('accountId', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('startDate', sa.String(length=10), nullable=False),
    sa.Column('endDate', sa.String(length=10), nullable=False),
    sa.Column('increment', sa.SmallInteger(), nullable=False),
    sa.Column('windowSize', sa.SmallInteger(), nullable=False),
    sa.Column('windowUnit', sa.String(length=1), nullable=False),
    sa.Column('processing', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('percentage', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('resultId', postgresql.UUID(as_uuid=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_executiontask_accountId'), 'executiontask', ['accountId'], unique=False)
    op.create_index(op.f('ix_executiontask_create_ts'), 'executiontask', ['create_ts'], unique=False)
    op.create_index(op.f('ix_executiontask_update_ts'), 'executiontask', ['update_ts'], unique=False)
    op.create_unique_constraint(None, 'account', ['id'])
    op.create_unique_constraint(None, 'token', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'token', type_='unique')
    op.drop_constraint(None, 'account', type_='unique')
    op.drop_index(op.f('ix_executiontask_update_ts'), table_name='executiontask')
    op.drop_index(op.f('ix_executiontask_create_ts'), table_name='executiontask')
    op.drop_index(op.f('ix_executiontask_accountId'), table_name='executiontask')
    op.drop_table('executiontask')
    op.drop_index(op.f('ix_executionresult_update_ts'), table_name='executionresult')
    op.drop_index(op.f('ix_executionresult_taskId'), table_name='executionresult')
    op.drop_index(op.f('ix_executionresult_create_ts'), table_name='executionresult')
    op.drop_index(op.f('ix_executionresult_accountId'), table_name='executionresult')
    op.drop_table('executionresult')
    op.drop_index(op.f('ix_datawindow_update_ts'), table_name='datawindow')
    op.drop_index(op.f('ix_datawindow_taskId'), table_name='datawindow')
    op.drop_index(op.f('ix_datawindow_resultId'), table_name='datawindow')
    op.drop_index(op.f('ix_datawindow_create_ts'), table_name='datawindow')
    op.drop_index(op.f('ix_datawindow_accountId'), table_name='datawindow')
    op.drop_table('datawindow')
    # ### end Alembic commands ###
