"""share

Revision ID: b9263973804f
Revises: fb13808f2c79
Create Date: 2022-01-06 14:56:48.805289

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b9263973804f'
down_revision = 'fb13808f2c79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sharerequest',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('create_ts', sa.BigInteger(), nullable=False),
    sa.Column('update_ts', sa.BigInteger(), nullable=False),
    sa.Column('accountId', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('taskId', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('resultId', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('code', sa.String(length=6), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_sharerequest_accountId'), 'sharerequest', ['accountId'], unique=False)
    op.create_index(op.f('ix_sharerequest_create_ts'), 'sharerequest', ['create_ts'], unique=False)
    op.create_index(op.f('ix_sharerequest_resultId'), 'sharerequest', ['resultId'], unique=False)
    op.create_index(op.f('ix_sharerequest_taskId'), 'sharerequest', ['taskId'], unique=False)
    op.create_index(op.f('ix_sharerequest_update_ts'), 'sharerequest', ['update_ts'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sharerequest_update_ts'), table_name='sharerequest')
    op.drop_index(op.f('ix_sharerequest_taskId'), table_name='sharerequest')
    op.drop_index(op.f('ix_sharerequest_resultId'), table_name='sharerequest')
    op.drop_index(op.f('ix_sharerequest_create_ts'), table_name='sharerequest')
    op.drop_index(op.f('ix_sharerequest_accountId'), table_name='sharerequest')
    op.drop_table('sharerequest')
    # ### end Alembic commands ###
