"""reset_column

Revision ID: fb13808f2c79
Revises: 688b33ed73a2
Create Date: 2021-12-25 14:45:29.976537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb13808f2c79'
down_revision = '688b33ed73a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'datawindow', ['id'])
    op.add_column('executionresult', sa.Column('eslapshed', sa.Integer(), server_default='0', nullable=False))
    op.drop_column('executionresult', 'timeUsed')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('executionresult', sa.Column('timeUsed', sa.SMALLINT(), server_default=sa.text("'0'::smallint"), autoincrement=False, nullable=False))
    op.drop_column('executionresult', 'eslapshed')
    op.drop_constraint(None, 'datawindow', type_='unique')
    # ### end Alembic commands ###
